pub enum Report {
    Rumble = 0x10,
    PlayerLeds,
    DataReportingMode,
    IRCameraEnable,
    SpeakerEnable,
    StatusInformationRequest,
    WriteMemoryAndRegisters,
    ReadMemoryAndRegisters,
    SpeakerData,
    SpeakerMute,
    IRCameraEnable2,
    StatusInformation,
    ReadMemoryAndRegistersData,
    Result,
    CoreButtons = 0x30,
    CoreButtonsAccelerometer,
    CoreButtonsExtension8,
    CoreButtonsAccelerometerIR12,
    CoreButtonsExtension19,
    CoreButtonsAccelerometerExtension16,
    CoreButtonsIR10Extension9,
    CoreButtonsAccelerometerIR10Extension6,
    Extension21 = 0x3d,
    Interleaved0,
    Interleaved1,
}